name: WastedJetpack
version: @version@
main: com.jerrybibo.wastedjetpack.WastedJetpack
authors: [Jerrybibo]
description: Wasted Jetpacks plugin.
website: jerrybibo.com
commands:
  jetpack:
    description: Gives the player a jetpack.
    usage: /<command> [durability]